name: CI Build + Unit Tests

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        settings:
          [
            { configuration: Debug, publishReadyToRun: False },
            { configuration: Release, publishReadyToRun: True },
          ]

    runs-on:
      windows-latest
      # For a list of available runner types, refer to
      # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: TestApp.sln

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install gitversion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: '5.x'

      - name: Determine version
        id: gitversion # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v0.9.15

      - name: Decrypt PFX file
        run: |
          echo "${{ secrets.WINDOWS_PFX_FILE }}" > cert.pfx.asc
          certutil -decode cert.pfx.asc cert.pfx

      - name: Add certificate to store
        run: certutil -user -q -p ${{ secrets.WINDOWS_PFX_PASSWORD }} -importpfx cert.pfx NoRoot

      - name: Restore dependencies
        run: dotnet restore -p:PublishReadyToRun=${{ matrix.settings.publishReadyToRun }}

      - name: Build solution
        run: dotnet publish -maxcpucount -p:RestorePackagesConfig=false \
               -p:Configuration=${{ matrix.settings.configuration }} \
               -p:PackageCertificateThumbprint="${{ secrets.WINDOWS_PFX_THUMBPRINT }}" \
               -f:net7.0-windows10.0.19041.0 \
               -verbosity:normal

      - name: Upload a build artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          path: .\**\AppPackages\**\*.*
          retention-days: 10
