name: CI Build + Unit Tests

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        settings:
          [
            { configuration: Debug, publishReadyToRun: False },
            { configuration: Release, publishReadyToRun: True },
          ]

    runs-on:
      windows-latest
      # For a list of available runner types, refer to
      # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: TestApp.sln

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Restore dependencies
        run: dotnet restore -p:PublishReadyToRun=${{ matrix.settings.publishReadyToRun }}

      - name: Build solution
        run: dotnet msbuild -maxcpucount -p:RestorePackagesConfig=false -p:Configuration=${{ matrix.settings.configuration }} -verbosity:normal
