name: CI Build + Unit Tests

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        settings:
          [
            { configuration: Debug, publishReadyToRun: False },
            { configuration: Release, publishReadyToRun: True },
          ]

    runs-on:
      windows-latest
      # For a list of available runner types, refer to
      # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: TestApp.sln

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v0.9.7

      - name: Restore dependencies
        run: dotnet restore -p:PublishReadyToRun=${{ matrix.settings.publishReadyToRun }}

      - name: Build solution
        run: dotnet msbuild -maxcpucount -p:RestorePackagesConfig=false -p:Configuration=${{ matrix.settings.configuration }} -verbosity:normal

      #- name: Publish solution
      #  run: dotnet publish TestApp/TestApp.csproj --configuration release /p:AssemblyVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} /p:FileVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} /p:InformationalVersion=${{ steps.gitversion.outputs.Sha }}

